inherit_from:
  - .rubocop-disable-default-enabled.yml
  - .rubocop-enable-default-disabled.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/spring
    - vendor/**/*

Lint/EndAlignment:
  AlignWith: variable

Style/CaseIndentation:
  IndentWhenRelativeTo: end

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/HashSyntax:
  Exclude:
    - lib/tasks/**/*.rake

Style/IndentArray:
  EnforcedStyle: consistent

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
