version: '3.7'

services:

  mongodb:
    image: mongo:3.4.7
    volumes:
      - 'mongodb_data:/data/db'
    ports:
      - 27017:27017
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.13
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'
    environment:
      - 'discovery.type=single-node'
      - 'cluster.name=register-elasticsearch'
      - 'bootstrap.memory_lock=true'
      - 'xpack.security.enabled=false'
      - 'xpack.monitoring.enabled=false'
      - 'xpack.ml.enabled=false'
      - 'xpack.watcher.enabled=false'
      - 'xpack.graph.enabled=false'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - 9200:9200
    restart: always

  redis:
    image: redis:4.0.9-alpine
    ports:
      - 6379:6379
    restart: always

  memcached:
    image: memcached:1.5-alpine
    ports:
      - 11211:11211

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

volumes:
  mongodb_data:
  es_data:
