version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/openownership/register

    docker:

      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test

      - image: mongo:3.4.7

      - image: elasticsearch:6.6.0

      - image: circleci/redis:4.0.9-alpine

    steps:

      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - app-bundle-v1-{{ checksum "Gemfile.lock" }}
            - app-bundle-v1-

      - run:
          name: Bundle install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: app-bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Restore yarn cache
      - restore_cache:
          keys:
            - app-yarn-v1-{{ checksum "yarn.lock" }}
            - app-yarn-v1-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: app-yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Download lib-cove-bods
          working_directory: ~/openownership
          command: |
              sudo apt update
              sudo apt-get install python3-pip python3-venv
              wget https://github.com/openownership/lib-cove-bods/archive/v0.5.0.zip
              unzip v0.5.0.zip

      # Restore pip cache
      - restore_cache:
          keys:
            - lib-cove-bods-v1-{{ checksum "~/openownership/lib-cove-bods-0.5.0/requirements.txt" }}
            - lib-cove-bods-v1-

      - run:
          name: 'Install lib-cove-bods'
          working_directory: ~/openownership/lib-cove-bods-0.5.0
          command: |
              python3 -m venv .ve
              source .ve/bin/activate
              pip3 install -r requirements.txt
              pip3 install -e .

      # Store pip cache
      - save_cache:
          key: lib-cove-bods-v1-{{ checksum "~/openownership/lib-cove-bods-0.5.0/requirements.txt" }}
          paths:
            - ~/.cache/pip

      - run:
          name: Wait for MongoDB
          command: dockerize -wait tcp://localhost:27017 -timeout 1m

      - run:
          name: Wait for ElasticSearch
          command: dockerize -wait tcp://localhost:9200 -timeout 1m

      - run:
          name: Wait for Redis
          command: dockerize -wait tcp://localhost:6379 -timeout 1m

      - run:
          command: bundle exec rspec --color --require spec_helper --format documentation spec
          environment:
            RAILS_ENV: test
            RACK_ENV: test
            LIB_COVE_BODS: ~/openownership/lib-cove-bods-0.5.0/.ve/bin/libcovebods
      - run: yarn test
      - run: bundle exec rubocop
      - run: bundle exec haml-lint .
      - run: yarn lint
