development:
  clients:
    default:
      database: open_ownership_register_development
      hosts:
        - localhost:27017
      options:
  options:
    scope_overwrite_exception: true
test:
  clients:
    default:
      database: open_ownership_register_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
