development:
  clients:
    default:
      database: open_ownership_register_development
      hosts:
        - <%= ENV['MONGODB_HOST'] %>
      options:
  options:
    scope_overwrite_exception: true
test:
  clients:
    default:
      database: open_ownership_register_test
      hosts:
        - <%= ENV['MONGODB_HOST'] %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      uri: <%= ENV[ENV['MONGODB_URI_ENV_NAME']] %>
      options:
        max_pool_size: 60
        connect_timeout: 10
        wait_queue_timeout: 10
